server:
  port: 8123

spring:
  application:
    name: dragonapi-interface
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
  main:
    allow-circular-references: true